// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgKjiftrgYj2ze2sPpvRHXDt_ofhl_2KY',
    appId: '1:409387980168:web:960685c89175f5cf49963d',
    messagingSenderId: '409387980168',
    projectId: 'book-app-af630',
    authDomain: 'book-app-af630.firebaseapp.com',
    storageBucket: 'book-app-af630.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6hT-MrEbwFSayuK57wFJ7LnZili_Sx8',
    appId: '1:409387980168:android:bb69cf952f0a0c9649963d',
    messagingSenderId: '409387980168',
    projectId: 'book-app-af630',
    storageBucket: 'book-app-af630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu2_S-heQRypVRwhVkjJb6G7aWQ-B3R0o',
    appId: '1:409387980168:ios:0ef3f4d2f066471e49963d',
    messagingSenderId: '409387980168',
    projectId: 'book-app-af630',
    storageBucket: 'book-app-af630.appspot.com',
    androidClientId: '409387980168-lc49qri6tcludn2f97vkg59qtuji7ugd.apps.googleusercontent.com',
    iosClientId: '409387980168-ah7j9and8ul00d0q3dss7drf44me6dbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
